#!/bin/bash

# Collect system information
HOSTNAME=$(hostname)
OS=$(source /etc/os-release; echo $PRETTY_NAME)
UPTIME=$(uptime -p)

# Collect hardware information
CPU=$(lscpu | grep "Model name" | cut -d ':' -f 2 | xargs)
RAM=$(free -h | grep Mem | awk '{print $2}')
DISK=$(lsblk -o NAME,SIZE,MODEL -d | tail -n +2)
VIDEO=$(lspci | grep VGA | awk -F ': ' '{print $2}')

# Collect network information
FQDN=$(hostname -f)
IP_ADDRESS=$(ip a | grep inet | grep -v inet6 | awk '{print $2}' | cut -d '/' -f 1 | head -n 1)
GATEWAY_IP=$(ip r | grep default | awk '{print $3}')
DNS_SERVER=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}')

# Collect system status
LOGGED_IN_USERS=$(who | awk '{print $1}' | sort | uniq | tr '\n' ',')
DISK_SPACE=$(df -h | awk '$NF=="/"{print $4}')
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVERAGES=$(uptime | awk -F 'load average:' '{ print $2 }')
LISTENING_PORTS=$(ss -tuln | awk '{print $5}' | cut -d ':' -f 2 | tail -n +2 | sort | uniq | tr '\n' ',')
UFW_STATUS=$(ufw status | grep Status | awk '{print $2}')

# Print the report
echo ""
echo "System Report generated by Sushma Gurung, $(date)"
echo ""
echo "System Information"
echo "------------------"
echo "Hostname: $HOSTNAME"
echo "OS: $OS"
echo "Uptime: $UPTIME"
echo ""
echo "Hardware Information"
echo "--------------------"
echo "CPU: $CPU"
echo "Ram: $RAM"
echo "Disk(s): $DISK"
echo "Video: $VIDEO"
echo ""
echo "Network Information"
echo "-------------------"
echo "FQDN: $FQDN"
echo "Host Address: $IP_ADDRESS"
echo "Gateway IP: $GATEWAY_IP"
echo "DNS Server: $DNS_SERVER"
echo ""
echo "System Status"
echo "-------------"
echo "Users Logged In: $LOGGED_IN_USERS"
echo "Disk Space: $DISK_SPACE"
echo "Process Count: $PROCESS_COUNT"
echo "Load Averages: $LOAD_AVERAGES"
echo "Listening Network Ports: $LISTENING_PORTS"
echo "UFW Status: $UFW_STATUS"
echo ""
